env:
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  atom: 'readonly'
  describe: 'readonly'
  beforeEach: 'readonly'
  it: 'readonly'
  expect: 'readonly'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
